/*
 * Port_Core.c
 *
 *  Created on: 01-Nov-2020
 *      Author: HP
 */

#include "Headers.h"

void Port_Init(void)
{

#if(ENABLE_PORT_A == TRUE)
	Port_Initialize_PortA();
#endif

#if(ENABLE_PORT_B == TRUE)
	Port_Initialize_PortB();
#endif

#if(ENABLE_PORT_C == TRUE)
	Port_Initialize_PortC();
#endif

#if(ENABLE_PORT_D == TRUE)
	Port_Initialize_PortD();
#endif

#if(ENABLE_PORT_E == TRUE)
	Port_Initialize_PortE();
#endif






}


#if(ENABLE_PORT_A == TRUE)

inline void Port_Clear_PortA(void)
{

	PORT_PCR(PORTA, 0, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 1, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 2, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 3, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 4, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 5, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 6, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 7, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 8, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 9, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 10, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 11, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 12, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 13, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 14, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 15, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 16, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 17, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 18, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 19, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 20, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 21, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 22, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 23, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 24, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 25, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 26, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 27, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 28, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 29, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 30, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTA, 31, 0, 0, 0, 0, 0, 0, 0);

}




inline void Port_Initialize_PortA(void)
{

	PCC-> PCCn[PCC_PORTA_INDEX] = PCC_PCCn_CGC_MASK;							/* Enable clock to PORT A*/

	Port_Clear_PortA();

	PORT_PCR(PORTA, \
			0u, \
			INTRP_TYPE_PORTA_0, \
			LOCK_REG_PORTA_0, \
			PIN_MUX_PORTA_0, \
			DRIVE_STRNTH_ON_PORTA_0, \
			PASSIVEFIL_ON_PORTA_0,	\
			PULL_RESISTOR_ON_PORTA_0,	\
			PULLUP_OR_DOWN_ON_PORTA_0);

	#if(PORT_A_0 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	0u);
	#elif(PORT_A_0 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	0u);
	#else

	#endif


	PORT_PCR(PORTA, \
			1u, \
			INTRP_TYPE_PORTA_1, \
			LOCK_REG_PORTA_1, \
			PIN_MUX_PORTA_1, \
			DRIVE_STRNTH_ON_PORTA_1, \
			PASSIVEFIL_ON_PORTA_1,	\
			PULL_RESISTOR_ON_PORTA_1,	\
			PULLUP_OR_DOWN_ON_PORTA_1);

	#if(PORT_A_1 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	1u);
	#elif(PORT_A_1 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	1u);
	#else

	#endif


	PORT_PCR(PORTA, \
	1u, \
	INTRP_TYPE_PORTA_2, \
	LOCK_REG_PORTA_2, \
	PIN_MUX_PORTA_2, \
	DRIVE_STRNTH_ON_PORTA_2, \
	PASSIVEFIL_ON_PORTA_2,	\
	PULL_RESISTOR_ON_PORTA_2,	\
	PULLUP_OR_DOWN_ON_PORTA_2);

	#if(PORT_A_2 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTA, 	2u);
	#elif(PORT_A_2 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTA, 	2u);
	#else

	#endif

	PORT_PCR(PORTA, \
				1u, \
				INTRP_TYPE_PORTA_3, \
				LOCK_REG_PORTA_3, \
				PIN_MUX_PORTA_3, \
				DRIVE_STRNTH_ON_PORTA_3, \
				PASSIVEFIL_ON_PORTA_3,	\
				PULL_RESISTOR_ON_PORTA_3,	\
				PULLUP_OR_DOWN_ON_PORTA_3);

	#if(PORT_A_3 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTA, 	3u);
	#elif(PORT_A_3 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTA, 	3u);
	#else

	#endif

	PORT_PCR(PORTA, \
				1u, \
				INTRP_TYPE_PORTA_4, \
				LOCK_REG_PORTA_4, \
				PIN_MUX_PORTA_4, \
				DRIVE_STRNTH_ON_PORTA_4, \
				PASSIVEFIL_ON_PORTA_4,	\
				PULL_RESISTOR_ON_PORTA_4,	\
				PULLUP_OR_DOWN_ON_PORTA_4);

	#if(PORT_A_4 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTA, 	4u);
	#elif(PORT_A_4 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTA, 	4u);
	#else

	#endif

	PORT_PCR(PORTA, \
			5u, \
			INTRP_TYPE_PORTA_5, \
			LOCK_REG_PORTA_5, \
			PIN_MUX_PORTA_5, \
			DRIVE_STRNTH_ON_PORTA_5, \
			PASSIVEFIL_ON_PORTA_5,	\
			PULL_RESISTOR_ON_PORTA_5,	\
			PULLUP_OR_DOWN_ON_PORTA_5);

	#if(PORT_A_5 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	5u);
	#elif(PORT_A_5 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	5u);
	#else

	#endif

	PORT_PCR(PORTA, \
			8u, \
			INTRP_TYPE_PORTA_6, \
			LOCK_REG_PORTA_6, \
			PIN_MUX_PORTA_6, \
			DRIVE_STRNTH_ON_PORTA_6, \
			PASSIVEFIL_ON_PORTA_6,	\
			PULL_RESISTOR_ON_PORTA_6,	\
			PULLUP_OR_DOWN_ON_PORTA_6);

	#if(PORT_A_6 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	6u);
	#elif(PORT_A_6 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	6u);
	#else

	#endif

	PORT_PCR(PORTA, \
			8u, \
			INTRP_TYPE_PORTA_7, \
			LOCK_REG_PORTA_7, \
			PIN_MUX_PORTA_7, \
			DRIVE_STRNTH_ON_PORTA_7, \
			PASSIVEFIL_ON_PORTA_7,	\
			PULL_RESISTOR_ON_PORTA_7,	\
			PULLUP_OR_DOWN_ON_PORTA_7);

	#if(PORT_A_7 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	7u);
	#elif(PORT_A_7 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	7u);
	#else

	#endif

	PORT_PCR(PORTA, \
			8u, \
			INTRP_TYPE_PORTA_8, \
			LOCK_REG_PORTA_8, \
			PIN_MUX_PORTA_8, \
			DRIVE_STRNTH_ON_PORTA_8, \
			PASSIVEFIL_ON_PORTA_8,	\
			PULL_RESISTOR_ON_PORTA_8,	\
			PULLUP_OR_DOWN_ON_PORTA_8);

	#if(PORT_A_8 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	8u);
	#elif(PORT_A_8 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	8u);
	#else

	#endif
	PORT_PCR(PORTA, \
			9u, \
			INTRP_TYPE_PORTA_9, \
			LOCK_REG_PORTA_9, \
			PIN_MUX_PORTA_9, \
			DRIVE_STRNTH_ON_PORTA_9, \
			PASSIVEFIL_ON_PORTA_9,	\
			PULL_RESISTOR_ON_PORTA_9,	\
			PULLUP_OR_DOWN_ON_PORTA_9);

	#if(PORT_A_9 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	9u);
	#elif(PORT_A_9 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	9u);
	#else

	#endif


	PORT_PCR(PORTA, \
			10u, \
			INTRP_TYPE_PORTA_10, \
			LOCK_REG_PORTA_10, \
			PIN_MUX_PORTA_10, \
			DRIVE_STRNTH_ON_PORTA_10, \
			PASSIVEFIL_ON_PORTA_10,	\
			PULL_RESISTOR_ON_PORTA_10,	\
			PULLUP_OR_DOWN_ON_PORTA_10);

	#if(PORT_A_10 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	10u);
	#elif(PORT_A_10 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	10u);
	#else

	#endif


	PORT_PCR(PORTA, \
			11u, \
			INTRP_TYPE_PORTA_11, \
			LOCK_REG_PORTA_11, \
			PIN_MUX_PORTA_11, \
			DRIVE_STRNTH_ON_PORTA_11, \
			PASSIVEFIL_ON_PORTA_11,	\
			PULL_RESISTOR_ON_PORTA_11,	\
			PULLUP_OR_DOWN_ON_PORTA_11);

	#if(PORT_A_11 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	11u);
	#elif(PORT_A_11 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	11u);
	#else

	#endif

	PORT_PCR(PORTA, \
			12u, \
			INTRP_TYPE_PORTA_12, \
			LOCK_REG_PORTA_12, \
			PIN_MUX_PORTA_12, \
			DRIVE_STRNTH_ON_PORTA_12, \
			PASSIVEFIL_ON_PORTA_12,	\
			PULL_RESISTOR_ON_PORTA_12,	\
			PULLUP_OR_DOWN_ON_PORTA_12);

	#if(PORT_A_12 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	12u);
	#elif(PORT_A_12 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	12u);
	#else

	#endif

	PORT_PCR(PORTA, \
			13u, \
			INTRP_TYPE_PORTA_13, \
			LOCK_REG_PORTA_13, \
			PIN_MUX_PORTA_13, \
			DRIVE_STRNTH_ON_PORTA_13, \
			PASSIVEFIL_ON_PORTA_13,	\
			PULL_RESISTOR_ON_PORTA_13,	\
			PULLUP_OR_DOWN_ON_PORTA_13);

	#if(PORT_A_13 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	13u);
	#elif(PORT_A_13 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	13u);
	#else

	#endif

	PORT_PCR(PORTA, \
			14u, \
			INTRP_TYPE_PORTA_14, \
			LOCK_REG_PORTA_14, \
			PIN_MUX_PORTA_14, \
			DRIVE_STRNTH_ON_PORTA_14, \
			PASSIVEFIL_ON_PORTA_14,	\
			PULL_RESISTOR_ON_PORTA_14,	\
			PULLUP_OR_DOWN_ON_PORTA_14);

	#if(PORT_A_14 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	14u);
	#elif(PORT_A_14 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	14u);
	#else

	#endif

	PORT_PCR(PORTA, \
			15u, \
			INTRP_TYPE_PORTA_15, \
			LOCK_REG_PORTA_15, \
			PIN_MUX_PORTA_15, \
			DRIVE_STRNTH_ON_PORTA_15, \
			PASSIVEFIL_ON_PORTA_15,	\
			PULL_RESISTOR_ON_PORTA_15,	\
			PULLUP_OR_DOWN_ON_PORTA_15);

	#if(PORT_A_15 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	15u);
	#elif(PORT_A_15 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	15u);
	#else

	#endif

	PORT_PCR(PORTA, \
			16u, \
			INTRP_TYPE_PORTA_16, \
			LOCK_REG_PORTA_16, \
			PIN_MUX_PORTA_16, \
			DRIVE_STRNTH_ON_PORTA_16, \
			PASSIVEFIL_ON_PORTA_16,	\
			PULL_RESISTOR_ON_PORTA_16,	\
			PULLUP_OR_DOWN_ON_PORTA_16);

	#if(PORT_A_16 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	16u);
	#elif(PORT_A_16 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	16u);
	#else

	#endif


	PORT_PCR(PORTA, \
			17u, \
			INTRP_TYPE_PORTA_17, \
			LOCK_REG_PORTA_17, \
			PIN_MUX_PORTA_17, \
			DRIVE_STRNTH_ON_PORTA_17, \
			PASSIVEFIL_ON_PORTA_17,	\
			PULL_RESISTOR_ON_PORTA_17,	\
			PULLUP_OR_DOWN_ON_PORTA_17);

	#if(PORT_A_17 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	17u);
	#elif(PORT_A_17 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	17u);
	#else

	#endif

	PORT_PCR(PORTA, \
			18u, \
			INTRP_TYPE_PORTA_18, \
			LOCK_REG_PORTA_18, \
			PIN_MUX_PORTA_18, \
			DRIVE_STRNTH_ON_PORTA_18, \
			PASSIVEFIL_ON_PORTA_18,	\
			PULL_RESISTOR_ON_PORTA_18,	\
			PULLUP_OR_DOWN_ON_PORTA_18);

	#if(PORT_A_18 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	18u);
	#elif(PORT_A_18 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	18u);
	#else

	#endif

	PORT_PCR(PORTA, \
			19u, \
			INTRP_TYPE_PORTA_19, \
			LOCK_REG_PORTA_19, \
			PIN_MUX_PORTA_19, \
			DRIVE_STRNTH_ON_PORTA_19, \
			PASSIVEFIL_ON_PORTA_19,	\
			PULL_RESISTOR_ON_PORTA_19,	\
			PULLUP_OR_DOWN_ON_PORTA_19);

	#if(PORT_A_19 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	19u);
	#elif(PORT_A_19 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	19u);
	#else

	#endif

	PORT_PCR(PORTA, \
			20u, \
			INTRP_TYPE_PORTA_20, \
			LOCK_REG_PORTA_20, \
			PIN_MUX_PORTA_20, \
			DRIVE_STRNTH_ON_PORTA_20, \
			PASSIVEFIL_ON_PORTA_20,	\
			PULL_RESISTOR_ON_PORTA_20,	\
			PULLUP_OR_DOWN_ON_PORTA_20);

	#if(PORT_A_20 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	20u);
	#elif(PORT_A_20 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	20u);
	#else

	#endif


	PORT_PCR(PORTA, \
			21u, \
			INTRP_TYPE_PORTA_21, \
			LOCK_REG_PORTA_21, \
			PIN_MUX_PORTA_21, \
			DRIVE_STRNTH_ON_PORTA_21, \
			PASSIVEFIL_ON_PORTA_21,	\
			PULL_RESISTOR_ON_PORTA_21,	\
			PULLUP_OR_DOWN_ON_PORTA_21);

	#if(PORT_A_21 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	21u);
	#elif(PORT_A_21 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	21u);
	#else

	#endif

	PORT_PCR(PORTA, \
			22u, \
			INTRP_TYPE_PORTA_22, \
			LOCK_REG_PORTA_22, \
			PIN_MUX_PORTA_22, \
			DRIVE_STRNTH_ON_PORTA_22, \
			PASSIVEFIL_ON_PORTA_22,	\
			PULL_RESISTOR_ON_PORTA_22,	\
			PULLUP_OR_DOWN_ON_PORTA_22);

	#if(PORT_A_22 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	22u);
	#elif(PORT_A_22 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	22u);
	#else

	#endif

	PORT_PCR(PORTA, \
			23u, \
			INTRP_TYPE_PORTA_23, \
			LOCK_REG_PORTA_23, \
			PIN_MUX_PORTA_23, \
			DRIVE_STRNTH_ON_PORTA_23, \
			PASSIVEFIL_ON_PORTA_23,	\
			PULL_RESISTOR_ON_PORTA_23,	\
			PULLUP_OR_DOWN_ON_PORTA_23);

	#if(PORT_A_23 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	23u);
	#elif(PORT_A_23 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	23u);
	#else

	#endif


	PORT_PCR(PORTA, \
			24u, \
			INTRP_TYPE_PORTA_24, \
			LOCK_REG_PORTA_24, \
			PIN_MUX_PORTA_24, \
			DRIVE_STRNTH_ON_PORTA_24, \
			PASSIVEFIL_ON_PORTA_24,	\
			PULL_RESISTOR_ON_PORTA_24,	\
			PULLUP_OR_DOWN_ON_PORTA_24);

	#if(PORT_A_24 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	24u);
	#elif(PORT_A_24 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	24u);
	#else

	#endif



	PORT_PCR(PORTA, \
			25u, \
			INTRP_TYPE_PORTA_25, \
			LOCK_REG_PORTA_25, \
			PIN_MUX_PORTA_25, \
			DRIVE_STRNTH_ON_PORTA_25, \
			PASSIVEFIL_ON_PORTA_25,	\
			PULL_RESISTOR_ON_PORTA_25,	\
			PULLUP_OR_DOWN_ON_PORTA_25);

	#if(PORT_A_25 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	25u);
	#elif(PORT_A_25 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	25u);
	#else

	#endif

	PORT_PCR(PORTA, \
			26u, \
			INTRP_TYPE_PORTA_26, \
			LOCK_REG_PORTA_26, \
			PIN_MUX_PORTA_26, \
			DRIVE_STRNTH_ON_PORTA_26, \
			PASSIVEFIL_ON_PORTA_26,	\
			PULL_RESISTOR_ON_PORTA_26,	\
			PULLUP_OR_DOWN_ON_PORTA_26);

	#if(PORT_A_26 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	26u);
	#elif(PORT_A_26 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	26u);
	#else

	#endif

	PORT_PCR(PORTA, \
			27u, \
			INTRP_TYPE_PORTA_27, \
			LOCK_REG_PORTA_27, \
			PIN_MUX_PORTA_27, \
			DRIVE_STRNTH_ON_PORTA_27, \
			PASSIVEFIL_ON_PORTA_27,	\
			PULL_RESISTOR_ON_PORTA_27,	\
			PULLUP_OR_DOWN_ON_PORTA_27);

	#if(PORT_A_27 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	27u);
	#elif(PORT_A_27 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	27u);
	#else

	#endif

	PORT_PCR(PORTA, \
			28u, \
			INTRP_TYPE_PORTA_28, \
			LOCK_REG_PORTA_28, \
			PIN_MUX_PORTA_28, \
			DRIVE_STRNTH_ON_PORTA_28, \
			PASSIVEFIL_ON_PORTA_28,	\
			PULL_RESISTOR_ON_PORTA_28,	\
			PULLUP_OR_DOWN_ON_PORTA_28);

	#if(PORT_A_28 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	28u);
	#elif(PORT_A_28 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	28u);
	#else

	#endif

	PORT_PCR(PORTA, \
			29u, \
			INTRP_TYPE_PORTA_29, \
			LOCK_REG_PORTA_29, \
			PIN_MUX_PORTA_29, \
			DRIVE_STRNTH_ON_PORTA_29, \
			PASSIVEFIL_ON_PORTA_29,	\
			PULL_RESISTOR_ON_PORTA_29,	\
			PULLUP_OR_DOWN_ON_PORTA_29);

	#if(PORT_A_29 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	29u);
	#elif(PORT_A_29 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	29u);
	#else

	#endif

	PORT_PCR(PORTA, \
			30u, \
			INTRP_TYPE_PORTA_30, \
			LOCK_REG_PORTA_30, \
			PIN_MUX_PORTA_30, \
			DRIVE_STRNTH_ON_PORTA_30, \
			PASSIVEFIL_ON_PORTA_30,	\
			PULL_RESISTOR_ON_PORTA_30,	\
			PULLUP_OR_DOWN_ON_PORTA_30);

	#if(PORT_A_30 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	30u);
	#elif(PORT_A_30 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	30u);
	#else

	#endif


	PORT_PCR(PORTA, \
			31u, \
			INTRP_TYPE_PORTA_31, \
			LOCK_REG_PORTA_31, \
			PIN_MUX_PORTA_31, \
			DRIVE_STRNTH_ON_PORTA_31, \
			PASSIVEFIL_ON_PORTA_31,	\
			PULL_RESISTOR_ON_PORTA_31,	\
			PULLUP_OR_DOWN_ON_PORTA_31);

	#if(PORT_A_31 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTA, 	31u);
	#elif(PORT_A_31 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTA, 	31u);
	#else

	#endif



}

#endif

#if(ENABLE_PORT_B == TRUE)


inline void Port_Clear_PortB(void)
{

	PORT_PCR(PORTB, 0, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 1, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 2, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 3, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 4, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 5, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 6, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 7, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 8, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 9, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 10, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 11, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 12, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 13, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 14, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 15, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 16, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 17, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 18, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 20, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 22, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 23, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 24, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 25, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 26, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 27, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 28, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 29, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 30, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTB, 31, 0, 0, 0, 0, 0, 0, 0);

}


inline void Port_Initialize_PortB(void)
{

	PCC-> PCCn[PCC_PORTB_INDEX] = PCC_PCCn_CGC_MASK;							/* Enable clock to PORT B*/

	Port_Clear_PortB();

	PORT_PCR(PORTB, \
			0u, \
			INTRP_TYPE_PORTB_0, \
			LOCK_REG_PORTB_0, \
			PIN_MUX_PORTB_0, \
			DRIVE_STRNTH_ON_PORTB_0, \
			PASSIVEFIL_ON_PORTB_0,	\
			PULL_RESISTOR_ON_PORTB_0,	\
			PULLUP_OR_DOWN_ON_PORTB_0);

	#if(PORT_B_0 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	0u);
	#elif(PORT_B_0 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	0u);
	#else

	#endif


	PORT_PCR(PORTB, \
			1u, \
			INTRP_TYPE_PORTB_1, \
			LOCK_REG_PORTB_1, \
			PIN_MUX_PORTB_1, \
			DRIVE_STRNTH_ON_PORTB_1, \
			PASSIVEFIL_ON_PORTB_1,	\
			PULL_RESISTOR_ON_PORTB_1,	\
			PULLUP_OR_DOWN_ON_PORTB_1);

	#if(PORT_B_1 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	1u);
	#elif(PORT_B_1 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	1u);
	#else

	#endif


	PORT_PCR(PORTB, \
	1u, \
	INTRP_TYPE_PORTB_2, \
	LOCK_REG_PORTB_2, \
	PIN_MUX_PORTB_2, \
	DRIVE_STRNTH_ON_PORTB_2, \
	PASSIVEFIL_ON_PORTB_2,	\
	PULL_RESISTOR_ON_PORTB_2,	\
	PULLUP_OR_DOWN_ON_PORTB_2);

	#if(PORT_B_2 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTB, 	2u);
	#elif(PORT_B_2 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTB, 	2u);
	#else

	#endif

	PORT_PCR(PORTB, \
				1u, \
				INTRP_TYPE_PORTB_3, \
				LOCK_REG_PORTB_3, \
				PIN_MUX_PORTB_3, \
				DRIVE_STRNTH_ON_PORTB_3, \
				PASSIVEFIL_ON_PORTB_3,	\
				PULL_RESISTOR_ON_PORTB_3,	\
				PULLUP_OR_DOWN_ON_PORTB_3);

	#if(PORT_B_3 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTB, 	3u);
	#elif(PORT_B_3 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTB, 	3u);
	#else

	#endif

	PORT_PCR(PORTB, \
				1u, \
				INTRP_TYPE_PORTB_4, \
				LOCK_REG_PORTB_4, \
				PIN_MUX_PORTB_4, \
				DRIVE_STRNTH_ON_PORTB_4, \
				PASSIVEFIL_ON_PORTB_4,	\
				PULL_RESISTOR_ON_PORTB_4,	\
				PULLUP_OR_DOWN_ON_PORTB_4);

	#if(PORT_B_4 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTB, 	4u);
	#elif(PORT_B_4 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTB, 	4u);
	#else

	#endif

	PORT_PCR(PORTB, \
			5u, \
			INTRP_TYPE_PORTB_5, \
			LOCK_REG_PORTB_5, \
			PIN_MUX_PORTB_5, \
			DRIVE_STRNTH_ON_PORTB_5, \
			PASSIVEFIL_ON_PORTB_5,	\
			PULL_RESISTOR_ON_PORTB_5,	\
			PULLUP_OR_DOWN_ON_PORTB_5);

	#if(PORT_B_5 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	5u);
	#elif(PORT_B_5 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	5u);
	#else

	#endif

	PORT_PCR(PORTB, \
			8u, \
			INTRP_TYPE_PORTB_6, \
			LOCK_REG_PORTB_6, \
			PIN_MUX_PORTB_6, \
			DRIVE_STRNTH_ON_PORTB_6, \
			PASSIVEFIL_ON_PORTB_6,	\
			PULL_RESISTOR_ON_PORTB_6,	\
			PULLUP_OR_DOWN_ON_PORTB_6);

	#if(PORT_B_6 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	6u);
	#elif(PORT_B_6 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	6u);
	#else

	#endif

	PORT_PCR(PORTB, \
			8u, \
			INTRP_TYPE_PORTB_7, \
			LOCK_REG_PORTB_7, \
			PIN_MUX_PORTB_7, \
			DRIVE_STRNTH_ON_PORTB_7, \
			PASSIVEFIL_ON_PORTB_7,	\
			PULL_RESISTOR_ON_PORTB_7,	\
			PULLUP_OR_DOWN_ON_PORTB_7);

	#if(PORT_B_7 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	7u);
	#elif(PORT_B_7 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	7u);
	#else

	#endif

	PORT_PCR(PORTB, \
			8u, \
			INTRP_TYPE_PORTB_8, \
			LOCK_REG_PORTB_8, \
			PIN_MUX_PORTB_8, \
			DRIVE_STRNTH_ON_PORTB_8, \
			PASSIVEFIL_ON_PORTB_8,	\
			PULL_RESISTOR_ON_PORTB_8,	\
			PULLUP_OR_DOWN_ON_PORTB_8);

	#if(PORT_B_8 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	8u);
	#elif(PORT_B_8 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	8u);
	#else

	#endif
	PORT_PCR(PORTB, \
			9u, \
			INTRP_TYPE_PORTB_9, \
			LOCK_REG_PORTB_9, \
			PIN_MUX_PORTB_9, \
			DRIVE_STRNTH_ON_PORTB_9, \
			PASSIVEFIL_ON_PORTB_9,	\
			PULL_RESISTOR_ON_PORTB_9,	\
			PULLUP_OR_DOWN_ON_PORTB_9);

	#if(PORT_B_9 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	9u);
	#elif(PORT_B_9 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	9u);
	#else

	#endif


	PORT_PCR(PORTB, \
			10u, \
			INTRP_TYPE_PORTB_10, \
			LOCK_REG_PORTB_10, \
			PIN_MUX_PORTB_10, \
			DRIVE_STRNTH_ON_PORTB_10, \
			PASSIVEFIL_ON_PORTB_10,	\
			PULL_RESISTOR_ON_PORTB_10,	\
			PULLUP_OR_DOWN_ON_PORTB_10);

	#if(PORT_B_10 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	10u);
	#elif(PORT_B_10 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	10u);
	#else

	#endif


	PORT_PCR(PORTB, \
			11u, \
			INTRP_TYPE_PORTB_11, \
			LOCK_REG_PORTB_11, \
			PIN_MUX_PORTB_11, \
			DRIVE_STRNTH_ON_PORTB_11, \
			PASSIVEFIL_ON_PORTB_11,	\
			PULL_RESISTOR_ON_PORTB_11,	\
			PULLUP_OR_DOWN_ON_PORTB_11);

	#if(PORT_B_11 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	11u);
	#elif(PORT_B_11 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	11u);
	#else

	#endif

	PORT_PCR(PORTB, \
			12u, \
			INTRP_TYPE_PORTB_12, \
			LOCK_REG_PORTB_12, \
			PIN_MUX_PORTB_12, \
			DRIVE_STRNTH_ON_PORTB_12, \
			PASSIVEFIL_ON_PORTB_12,	\
			PULL_RESISTOR_ON_PORTB_12,	\
			PULLUP_OR_DOWN_ON_PORTB_12);

	#if(PORT_B_12 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	12u);
	#elif(PORT_B_12 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	12u);
	#else

	#endif

	PORT_PCR(PORTB, \
			13u, \
			INTRP_TYPE_PORTB_13, \
			LOCK_REG_PORTB_13, \
			PIN_MUX_PORTB_13, \
			DRIVE_STRNTH_ON_PORTB_13, \
			PASSIVEFIL_ON_PORTB_13,	\
			PULL_RESISTOR_ON_PORTB_13,	\
			PULLUP_OR_DOWN_ON_PORTB_13);

	#if(PORT_B_13 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	13u);
	#elif(PORT_B_13 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	13u);
	#else

	#endif

	PORT_PCR(PORTB, \
			14u, \
			INTRP_TYPE_PORTB_14, \
			LOCK_REG_PORTB_14, \
			PIN_MUX_PORTB_14, \
			DRIVE_STRNTH_ON_PORTB_14, \
			PASSIVEFIL_ON_PORTB_14,	\
			PULL_RESISTOR_ON_PORTB_14,	\
			PULLUP_OR_DOWN_ON_PORTB_14);

	#if(PORT_B_14 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	14u);
	#elif(PORT_B_14 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	14u);
	#else

	#endif

	PORT_PCR(PORTB, \
			15u, \
			INTRP_TYPE_PORTB_15, \
			LOCK_REG_PORTB_15, \
			PIN_MUX_PORTB_15, \
			DRIVE_STRNTH_ON_PORTB_15, \
			PASSIVEFIL_ON_PORTB_15,	\
			PULL_RESISTOR_ON_PORTB_15,	\
			PULLUP_OR_DOWN_ON_PORTB_15);

	#if(PORT_B_15 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	15u);
	#elif(PORT_B_15 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	15u);
	#else

	#endif

	PORT_PCR(PORTB, \
			16u, \
			INTRP_TYPE_PORTB_16, \
			LOCK_REG_PORTB_16, \
			PIN_MUX_PORTB_16, \
			DRIVE_STRNTH_ON_PORTB_16, \
			PASSIVEFIL_ON_PORTB_16,	\
			PULL_RESISTOR_ON_PORTB_16,	\
			PULLUP_OR_DOWN_ON_PORTB_16);

	#if(PORT_B_16 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	16u);
	#elif(PORT_B_16 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	16u);
	#else

	#endif


	PORT_PCR(PORTB, \
			17u, \
			INTRP_TYPE_PORTB_17, \
			LOCK_REG_PORTB_17, \
			PIN_MUX_PORTB_17, \
			DRIVE_STRNTH_ON_PORTB_17, \
			PASSIVEFIL_ON_PORTB_17,	\
			PULL_RESISTOR_ON_PORTB_17,	\
			PULLUP_OR_DOWN_ON_PORTB_17);

	#if(PORT_B_17 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	17u);
	#elif(PORT_B_17 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	17u);
	#else

	#endif

	PORT_PCR(PORTB, \
			18u, \
			INTRP_TYPE_PORTB_18, \
			LOCK_REG_PORTB_18, \
			PIN_MUX_PORTB_18, \
			DRIVE_STRNTH_ON_PORTB_18, \
			PASSIVEFIL_ON_PORTB_18,	\
			PULL_RESISTOR_ON_PORTB_18,	\
			PULLUP_OR_DOWN_ON_PORTB_18);

	#if(PORT_B_18 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	18u);
	#elif(PORT_B_18 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	18u);
	#else

	#endif

	PORT_PCR(PORTB, \
			19u, \
			INTRP_TYPE_PORTB_19, \
			LOCK_REG_PORTB_19, \
			PIN_MUX_PORTB_19, \
			DRIVE_STRNTH_ON_PORTB_19, \
			PASSIVEFIL_ON_PORTB_19,	\
			PULL_RESISTOR_ON_PORTB_19,	\
			PULLUP_OR_DOWN_ON_PORTB_19);

	#if(PORT_B_19 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	19u);
	#elif(PORT_B_19 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	19u);
	#else

	#endif

	PORT_PCR(PORTB, \
			20u, \
			INTRP_TYPE_PORTB_20, \
			LOCK_REG_PORTB_20, \
			PIN_MUX_PORTB_20, \
			DRIVE_STRNTH_ON_PORTB_20, \
			PASSIVEFIL_ON_PORTB_20,	\
			PULL_RESISTOR_ON_PORTB_20,	\
			PULLUP_OR_DOWN_ON_PORTB_20);

	#if(PORT_B_20 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	20u);
	#elif(PORT_B_20 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	20u);
	#else

	#endif


	PORT_PCR(PORTB, \
			21u, \
			INTRP_TYPE_PORTB_21, \
			LOCK_REG_PORTB_21, \
			PIN_MUX_PORTB_21, \
			DRIVE_STRNTH_ON_PORTB_21, \
			PASSIVEFIL_ON_PORTB_21,	\
			PULL_RESISTOR_ON_PORTB_21,	\
			PULLUP_OR_DOWN_ON_PORTB_21);

	#if(PORT_B_21 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	21u);
	#elif(PORT_B_21 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	21u);
	#else

	#endif

	PORT_PCR(PORTB, \
			22u, \
			INTRP_TYPE_PORTB_22, \
			LOCK_REG_PORTB_22, \
			PIN_MUX_PORTB_22, \
			DRIVE_STRNTH_ON_PORTB_22, \
			PASSIVEFIL_ON_PORTB_22,	\
			PULL_RESISTOR_ON_PORTB_22,	\
			PULLUP_OR_DOWN_ON_PORTB_22);

	#if(PORT_B_22 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	22u);
	#elif(PORT_B_22 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	22u);
	#else

	#endif

	PORT_PCR(PORTB, \
			23u, \
			INTRP_TYPE_PORTB_23, \
			LOCK_REG_PORTB_23, \
			PIN_MUX_PORTB_23, \
			DRIVE_STRNTH_ON_PORTB_23, \
			PASSIVEFIL_ON_PORTB_23,	\
			PULL_RESISTOR_ON_PORTB_23,	\
			PULLUP_OR_DOWN_ON_PORTB_23);

	#if(PORT_B_23 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	23u);
	#elif(PORT_B_23 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	23u);
	#else

	#endif


	PORT_PCR(PORTB, \
			24u, \
			INTRP_TYPE_PORTB_24, \
			LOCK_REG_PORTB_24, \
			PIN_MUX_PORTB_24, \
			DRIVE_STRNTH_ON_PORTB_24, \
			PASSIVEFIL_ON_PORTB_24,	\
			PULL_RESISTOR_ON_PORTB_24,	\
			PULLUP_OR_DOWN_ON_PORTB_24);

	#if(PORT_B_24 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	24u);
	#elif(PORT_B_24 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	24u);
	#else

	#endif



	PORT_PCR(PORTB, \
			25u, \
			INTRP_TYPE_PORTB_25, \
			LOCK_REG_PORTB_25, \
			PIN_MUX_PORTB_25, \
			DRIVE_STRNTH_ON_PORTB_25, \
			PASSIVEFIL_ON_PORTB_25,	\
			PULL_RESISTOR_ON_PORTB_25,	\
			PULLUP_OR_DOWN_ON_PORTB_25);

	#if(PORT_B_25 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	25u);
	#elif(PORT_B_25 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	25u);
	#else

	#endif

	PORT_PCR(PORTB, \
			26u, \
			INTRP_TYPE_PORTB_26, \
			LOCK_REG_PORTB_26, \
			PIN_MUX_PORTB_26, \
			DRIVE_STRNTH_ON_PORTB_26, \
			PASSIVEFIL_ON_PORTB_26,	\
			PULL_RESISTOR_ON_PORTB_26,	\
			PULLUP_OR_DOWN_ON_PORTB_26);

	#if(PORT_B_26 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	26u);
	#elif(PORT_B_26 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	26u);
	#else

	#endif

	PORT_PCR(PORTB, \
			27u, \
			INTRP_TYPE_PORTB_27, \
			LOCK_REG_PORTB_27, \
			PIN_MUX_PORTB_27, \
			DRIVE_STRNTH_ON_PORTB_27, \
			PASSIVEFIL_ON_PORTB_27,	\
			PULL_RESISTOR_ON_PORTB_27,	\
			PULLUP_OR_DOWN_ON_PORTB_27);

	#if(PORT_B_27 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	27u);
	#elif(PORT_B_27 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	27u);
	#else

	#endif

	PORT_PCR(PORTB, \
			28u, \
			INTRP_TYPE_PORTB_28, \
			LOCK_REG_PORTB_28, \
			PIN_MUX_PORTB_28, \
			DRIVE_STRNTH_ON_PORTB_28, \
			PASSIVEFIL_ON_PORTB_28,	\
			PULL_RESISTOR_ON_PORTB_28,	\
			PULLUP_OR_DOWN_ON_PORTB_28);

	#if(PORT_B_28 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	28u);
	#elif(PORT_B_28 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	28u);
	#else

	#endif

	PORT_PCR(PORTB, \
			29u, \
			INTRP_TYPE_PORTB_29, \
			LOCK_REG_PORTB_29, \
			PIN_MUX_PORTB_29, \
			DRIVE_STRNTH_ON_PORTB_29, \
			PASSIVEFIL_ON_PORTB_29,	\
			PULL_RESISTOR_ON_PORTB_29,	\
			PULLUP_OR_DOWN_ON_PORTB_29);

	#if(PORT_B_29 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	29u);
	#elif(PORT_B_29 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	29u);
	#else

	#endif

	PORT_PCR(PORTB, \
			30u, \
			INTRP_TYPE_PORTB_30, \
			LOCK_REG_PORTB_30, \
			PIN_MUX_PORTB_30, \
			DRIVE_STRNTH_ON_PORTB_30, \
			PASSIVEFIL_ON_PORTB_30,	\
			PULL_RESISTOR_ON_PORTB_30,	\
			PULLUP_OR_DOWN_ON_PORTB_30);

	#if(PORT_B_30 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	30u);
	#elif(PORT_B_30 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	30u);
	#else

	#endif


	PORT_PCR(PORTB, \
			31u, \
			INTRP_TYPE_PORTB_31, \
			LOCK_REG_PORTB_31, \
			PIN_MUX_PORTB_31, \
			DRIVE_STRNTH_ON_PORTB_31, \
			PASSIVEFIL_ON_PORTB_31,	\
			PULL_RESISTOR_ON_PORTB_31,	\
			PULLUP_OR_DOWN_ON_PORTB_31);

	#if(PORT_B_31 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTB, 	31u);
	#elif(PORT_B_31 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTB, 	31u);
	#else

	#endif





}

#endif



#if(ENABLE_PORT_C == TRUE)


inline void Port_Clear_PortC(void)
{

	PORT_PCR(PORTC, 0, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 1, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 2, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 3, 0, 0, 0, 0, 0, 0, 0);
#if(DEBUG_MODE == FALSE)
	PORT_PCR(PORTC, 4, 0, 0, 0, 0, 0, 0, 0);
#endif
	PORT_PCR(PORTC, 5, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 6, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 7, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 8, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 9, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 10, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 11, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 12, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 13, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 14, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 15, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 16, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 17, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 18, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 19, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 20, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 21, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 22, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 23, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 24, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 25, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 26, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 27, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 28, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 29, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 30, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTC, 31, 0, 0, 0, 0, 0, 0, 0);

}

inline void Port_Initialize_PortC(void)
{

	PCC-> PCCn[PCC_PORTC_INDEX] = PCC_PCCn_CGC_MASK;							/* Enable clock to PORT C*/

	Port_Clear_PortC();

	PORT_PCR(PORTC, \
			0u, \
			INTRP_TYPE_PORTC_0, \
			LOCK_REG_PORTC_0, \
			PIN_MUX_PORTC_0, \
			DRIVE_STRNTH_ON_PORTC_0, \
			PASSIVEFIL_ON_PORTC_0,	\
			PULL_RESISTOR_ON_PORTC_0,	\
			PULLUP_OR_DOWN_ON_PORTC_0);

	#if(PORT_C_0 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	0u);
	#elif(PORT_C_0 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	0u);
	#else

	#endif


	PORT_PCR(PORTC, \
			1u, \
			INTRP_TYPE_PORTC_1, \
			LOCK_REG_PORTC_1, \
			PIN_MUX_PORTC_1, \
			DRIVE_STRNTH_ON_PORTC_1, \
			PASSIVEFIL_ON_PORTC_1,	\
			PULL_RESISTOR_ON_PORTC_1,	\
			PULLUP_OR_DOWN_ON_PORTC_1);

	#if(PORT_C_1 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	1u);
	#elif(PORT_C_1 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	1u);
	#else

	#endif


	PORT_PCR(PORTC, \
	1u, \
	INTRP_TYPE_PORTC_2, \
	LOCK_REG_PORTC_2, \
	PIN_MUX_PORTC_2, \
	DRIVE_STRNTH_ON_PORTC_2, \
	PASSIVEFIL_ON_PORTC_2,	\
	PULL_RESISTOR_ON_PORTC_2,	\
	PULLUP_OR_DOWN_ON_PORTC_2);

	#if(PORT_C_2 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTC, 	2u);
	#elif(PORT_C_2 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTC, 	2u);
	#else

	#endif

	PORT_PCR(PORTC, \
				3u, \
				INTRP_TYPE_PORTC_3, \
				LOCK_REG_PORTC_3, \
				PIN_MUX_PORTC_3, \
				DRIVE_STRNTH_ON_PORTC_3, \
				PASSIVEFIL_ON_PORTC_3,	\
				PULL_RESISTOR_ON_PORTC_3,	\
				PULLUP_OR_DOWN_ON_PORTC_3);

	#if(PORT_C_3 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTC, 	3u);
	#elif(PORT_C_3 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTC, 	3u);
	#else

	#endif

#if(DEBUG_MODE == FALSE)

	PORT_PCR(PORTC, \
				4u, \
				INTRP_TYPE_PORTC_4, \
				LOCK_REG_PORTC_4, \
				PIN_MUX_PORTC_4, \
				DRIVE_STRNTH_ON_PORTC_4, \
				PASSIVEFIL_ON_PORTC_4,	\
				PULL_RESISTOR_ON_PORTC_4,	\
				PULLUP_OR_DOWN_ON_PORTC_4);

	#if(PORT_C_4 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTC, 	4u);
	#elif(PORT_C_4 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTC, 	4u);
	#else

	#endif

#endif

	PORT_PCR(PORTC, \
			5u, \
			INTRP_TYPE_PORTC_5, \
			LOCK_REG_PORTC_5, \
			PIN_MUX_PORTC_5, \
			DRIVE_STRNTH_ON_PORTC_5, \
			PASSIVEFIL_ON_PORTC_5,	\
			PULL_RESISTOR_ON_PORTC_5,	\
			PULLUP_OR_DOWN_ON_PORTC_5);

	#if(PORT_C_5 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	5u);
	#elif(PORT_C_5 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	5u);
	#else

	#endif

	PORT_PCR(PORTC, \
			6u, \
			INTRP_TYPE_PORTC_6, \
			LOCK_REG_PORTC_6, \
			PIN_MUX_PORTC_6, \
			DRIVE_STRNTH_ON_PORTC_6, \
			PASSIVEFIL_ON_PORTC_6,	\
			PULL_RESISTOR_ON_PORTC_6,	\
			PULLUP_OR_DOWN_ON_PORTC_6);

//	#if(PORT_C_6 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	6u);
//	#elif(PORT_C_6 == OUTPUT)
//			SET_PIN_DIRECTION_OUTPUT(PTC, 	6u);
//	#else
//
//	#endif

	PORT_PCR(PORTC, \
			7u, \
			INTRP_TYPE_PORTC_7, \
			LOCK_REG_PORTC_7, \
			PIN_MUX_PORTC_7, \
			DRIVE_STRNTH_ON_PORTC_7, \
			PASSIVEFIL_ON_PORTC_7,	\
			PULL_RESISTOR_ON_PORTC_7,	\
			PULLUP_OR_DOWN_ON_PORTC_7);

//	#if(PORT_C_7 == INPUT)
//			SET_PIN_DIRECTION_INPUT(PTC, 	7u);
//	#elif(PORT_C_7 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	7u);
//	#else
//
//	#endif

	PORT_PCR(PORTC, \
			8u, \
			INTRP_TYPE_PORTC_8, \
			LOCK_REG_PORTC_8, \
			PIN_MUX_PORTC_8, \
			DRIVE_STRNTH_ON_PORTC_8, \
			PASSIVEFIL_ON_PORTC_8,	\
			PULL_RESISTOR_ON_PORTC_8,	\
			PULLUP_OR_DOWN_ON_PORTC_8);

	#if(PORT_C_8 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	8u);
	#elif(PORT_C_8 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	8u);
	#else

	#endif
	PORT_PCR(PORTC, \
			9u, \
			INTRP_TYPE_PORTC_9, \
			LOCK_REG_PORTC_9, \
			PIN_MUX_PORTC_9, \
			DRIVE_STRNTH_ON_PORTC_9, \
			PASSIVEFIL_ON_PORTC_9,	\
			PULL_RESISTOR_ON_PORTC_9,	\
			PULLUP_OR_DOWN_ON_PORTC_9);

	#if(PORT_C_9 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	9u);
	#elif(PORT_C_9 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	9u);
	#else

	#endif


	PORT_PCR(PORTC, \
			10u, \
			INTRP_TYPE_PORTC_10, \
			LOCK_REG_PORTC_10, \
			PIN_MUX_PORTC_10, \
			DRIVE_STRNTH_ON_PORTC_10, \
			PASSIVEFIL_ON_PORTC_10,	\
			PULL_RESISTOR_ON_PORTC_10,	\
			PULLUP_OR_DOWN_ON_PORTC_10);

	#if(PORT_C_10 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	10u);
	#elif(PORT_C_10 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	10u);
	#else

	#endif


	PORT_PCR(PORTC, \
			11u, \
			INTRP_TYPE_PORTC_11, \
			LOCK_REG_PORTC_11, \
			PIN_MUX_PORTC_11, \
			DRIVE_STRNTH_ON_PORTC_11, \
			PASSIVEFIL_ON_PORTC_11,	\
			PULL_RESISTOR_ON_PORTC_11,	\
			PULLUP_OR_DOWN_ON_PORTC_11);

	#if(PORT_C_11 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	11u);
	#elif(PORT_C_11 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	11u);
	#else

	#endif


	PORT_PCR(PORTC, \
			12u, \
			INTRP_TYPE_PORTC_12, \
			LOCK_REG_PORTC_12, \
			PIN_MUX_PORTC_12, \
			DRIVE_STRNTH_ON_PORTC_12, \
			PASSIVEFIL_ON_PORTC_12,	\
			PULL_RESISTOR_ON_PORTC_12,	\
			PULLUP_OR_DOWN_ON_PORTC_12);

	#if(PORT_C_12 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	12u);
	#elif(PORT_C_12 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	12u);
	#else

	#endif



	PORT_PCR(PORTC, \
			13u, \
			INTRP_TYPE_PORTC_13, \
			LOCK_REG_PORTC_13, \
			PIN_MUX_PORTC_13, \
			DRIVE_STRNTH_ON_PORTC_13, \
			PASSIVEFIL_ON_PORTC_13,	\
			PULL_RESISTOR_ON_PORTC_13,	\
			PULLUP_OR_DOWN_ON_PORTC_13);

	#if(PORT_C_13 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	13u);
	#elif(PORT_C_13 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	13u);
	#else

	#endif


	PORT_PCR(PORTC, \
			14u, \
			INTRP_TYPE_PORTC_14, \
			LOCK_REG_PORTC_14, \
			PIN_MUX_PORTC_14, \
			DRIVE_STRNTH_ON_PORTC_14, \
			PASSIVEFIL_ON_PORTC_14,	\
			PULL_RESISTOR_ON_PORTC_14,	\
			PULLUP_OR_DOWN_ON_PORTC_14);

	#if(PORT_C_14 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	14u);
	#elif(PORT_C_14 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	14u);
	#else

	#endif

	PORT_PCR(PORTC, \
			15u, \
			INTRP_TYPE_PORTC_15, \
			LOCK_REG_PORTC_15, \
			PIN_MUX_PORTC_15, \
			DRIVE_STRNTH_ON_PORTC_15, \
			PASSIVEFIL_ON_PORTC_15,	\
			PULL_RESISTOR_ON_PORTC_15,	\
			PULLUP_OR_DOWN_ON_PORTC_15);

	#if(PORT_C_15 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	15u);
	#elif(PORT_C_15 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	15u);
	#else

	#endif

	PORT_PCR(PORTC, \
			16u, \
			INTRP_TYPE_PORTC_16, \
			LOCK_REG_PORTC_16, \
			PIN_MUX_PORTC_16, \
			DRIVE_STRNTH_ON_PORTC_16, \
			PASSIVEFIL_ON_PORTC_16,	\
			PULL_RESISTOR_ON_PORTC_16,	\
			PULLUP_OR_DOWN_ON_PORTC_16);

	#if(PORT_C_16 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	16u);
	#elif(PORT_C_16 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	16u);
	#else

	#endif


	PORT_PCR(PORTC, \
			17u, \
			INTRP_TYPE_PORTC_17, \
			LOCK_REG_PORTC_17, \
			PIN_MUX_PORTC_17, \
			DRIVE_STRNTH_ON_PORTC_17, \
			PASSIVEFIL_ON_PORTC_17,	\
			PULL_RESISTOR_ON_PORTC_17,	\
			PULLUP_OR_DOWN_ON_PORTC_17);

	#if(PORT_C_17 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	17u);
	#elif(PORT_C_17 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	17u);
	#else

	#endif


#if(S32K146 | S32K148 == TRUE)

	PORT_PCR(PORTC, \
			18u, \
			INTRP_TYPE_PORTC_18, \
			LOCK_REG_PORTC_18, \
			PIN_MUX_PORTC_18, \
			DRIVE_STRNTH_ON_PORTC_18, \
			PASSIVEFIL_ON_PORTC_18,	\
			PULL_RESISTOR_ON_PORTC_18,	\
			PULLUP_OR_DOWN_ON_PORTC_18);

	#if(PORT_C_18 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	18u);
	#elif(PORT_C_18 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	18u);
	#else

	#endif

	PORT_PCR(PORTC, \
			19u, \
			INTRP_TYPE_PORTC_19, \
			LOCK_REG_PORTC_19, \
			PIN_MUX_PORTC_19, \
			DRIVE_STRNTH_ON_PORTC_19, \
			PASSIVEFIL_ON_PORTC_19,	\
			PULL_RESISTOR_ON_PORTC_19,	\
			PULLUP_OR_DOWN_ON_PORTC_19);

	#if(PORT_C_19 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	19u);
	#elif(PORT_C_19 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	19u);
	#else

	#endif

	PORT_PCR(PORTC, \
			20u, \
			INTRP_TYPE_PORTC_20, \
			LOCK_REG_PORTC_20, \
			PIN_MUX_PORTC_20, \
			DRIVE_STRNTH_ON_PORTC_20, \
			PASSIVEFIL_ON_PORTC_20,	\
			PULL_RESISTOR_ON_PORTC_20,	\
			PULLUP_OR_DOWN_ON_PORTC_20);

	#if(PORT_C_20 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	20u);
	#elif(PORT_C_20 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	20u);
	#else

	#endif


	PORT_PCR(PORTC, \
			21u, \
			INTRP_TYPE_PORTC_21, \
			LOCK_REG_PORTC_21, \
			PIN_MUX_PORTC_21, \
			DRIVE_STRNTH_ON_PORTC_21, \
			PASSIVEFIL_ON_PORTC_21,	\
			PULL_RESISTOR_ON_PORTC_21,	\
			PULLUP_OR_DOWN_ON_PORTC_21);

	#if(PORT_C_21 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	21u);
	#elif(PORT_C_21 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	21u);
	#else

	#endif

	PORT_PCR(PORTC, \
			22u, \
			INTRP_TYPE_PORTC_22, \
			LOCK_REG_PORTC_22, \
			PIN_MUX_PORTC_22, \
			DRIVE_STRNTH_ON_PORTC_22, \
			PASSIVEFIL_ON_PORTC_22,	\
			PULL_RESISTOR_ON_PORTC_22,	\
			PULLUP_OR_DOWN_ON_PORTC_22);

	#if(PORT_C_22 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	22u);
	#elif(PORT_C_22 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	22u);
	#else

	#endif

	PORT_PCR(PORTC, \
			23u, \
			INTRP_TYPE_PORTC_23, \
			LOCK_REG_PORTC_23, \
			PIN_MUX_PORTC_23, \
			DRIVE_STRNTH_ON_PORTC_23, \
			PASSIVEFIL_ON_PORTC_23,	\
			PULL_RESISTOR_ON_PORTC_23,	\
			PULLUP_OR_DOWN_ON_PORTC_23);

	#if(PORT_C_23 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	23u);
	#elif(PORT_C_23 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	23u);
	#else

	#endif

#endif  /*#if(S32K146 | S32K148 == TRUE) End*/

#if(S32K148 == TRUE)

	PORT_PCR(PORTC, \
			24u, \
			INTRP_TYPE_PORTC_24, \
			LOCK_REG_PORTC_24, \
			PIN_MUX_PORTC_24, \
			DRIVE_STRNTH_ON_PORTC_24, \
			PASSIVEFIL_ON_PORTC_24,	\
			PULL_RESISTOR_ON_PORTC_24,	\
			PULLUP_OR_DOWN_ON_PORTC_24);

	#if(PORT_C_24 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	24u);
	#elif(PORT_C_24 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	24u);
	#else

	#endif



	PORT_PCR(PORTC, \
			25u, \
			INTRP_TYPE_PORTC_25, \
			LOCK_REG_PORTC_25, \
			PIN_MUX_PORTC_25, \
			DRIVE_STRNTH_ON_PORTC_25, \
			PASSIVEFIL_ON_PORTC_25,	\
			PULL_RESISTOR_ON_PORTC_25,	\
			PULLUP_OR_DOWN_ON_PORTC_25);

	#if(PORT_C_25 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	25u);
	#elif(PORT_C_25 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	25u);
	#else

	#endif

	PORT_PCR(PORTC, \
			26u, \
			INTRP_TYPE_PORTC_26, \
			LOCK_REG_PORTC_26, \
			PIN_MUX_PORTC_26, \
			DRIVE_STRNTH_ON_PORTC_26, \
			PASSIVEFIL_ON_PORTC_26,	\
			PULL_RESISTOR_ON_PORTC_26,	\
			PULLUP_OR_DOWN_ON_PORTC_26);

	#if(PORT_C_26 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	26u);
	#elif(PORT_C_26 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	26u);
	#else

	#endif

	PORT_PCR(PORTC, \
			27u, \
			INTRP_TYPE_PORTC_27, \
			LOCK_REG_PORTC_27, \
			PIN_MUX_PORTC_27, \
			DRIVE_STRNTH_ON_PORTC_27, \
			PASSIVEFIL_ON_PORTC_27,	\
			PULL_RESISTOR_ON_PORTC_27,	\
			PULLUP_OR_DOWN_ON_PORTC_27);

	#if(PORT_C_27 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	27u);
	#elif(PORT_C_27 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	27u);
	#else

	#endif

	PORT_PCR(PORTC, \
			28u, \
			INTRP_TYPE_PORTC_28, \
			LOCK_REG_PORTC_28, \
			PIN_MUX_PORTC_28, \
			DRIVE_STRNTH_ON_PORTC_28, \
			PASSIVEFIL_ON_PORTC_28,	\
			PULL_RESISTOR_ON_PORTC_28,	\
			PULLUP_OR_DOWN_ON_PORTC_28);

	#if(PORT_C_28 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	28u);
	#elif(PORT_C_28 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	28u);
	#else

	#endif

	PORT_PCR(PORTC, \
			29u, \
			INTRP_TYPE_PORTC_29, \
			LOCK_REG_PORTC_29, \
			PIN_MUX_PORTC_29, \
			DRIVE_STRNTH_ON_PORTC_29, \
			PASSIVEFIL_ON_PORTC_29,	\
			PULL_RESISTOR_ON_PORTC_29,	\
			PULLUP_OR_DOWN_ON_PORTC_29);

	#if(PORT_C_29 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	29u);
	#elif(PORT_C_29 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	29u);
	#else

	#endif

	PORT_PCR(PORTC, \
			30u, \
			INTRP_TYPE_PORTC_30, \
			LOCK_REG_PORTC_30, \
			PIN_MUX_PORTC_30, \
			DRIVE_STRNTH_ON_PORTC_30, \
			PASSIVEFIL_ON_PORTC_30,	\
			PULL_RESISTOR_ON_PORTC_30,	\
			PULLUP_OR_DOWN_ON_PORTC_30);

	#if(PORT_C_30 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	30u);
	#elif(PORT_C_30 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	30u);
	#else

	#endif


	PORT_PCR(PORTC, \
			31u, \
			INTRP_TYPE_PORTC_31, \
			LOCK_REG_PORTC_31, \
			PIN_MUX_PORTC_31, \
			DRIVE_STRNTH_ON_PORTC_31, \
			PASSIVEFIL_ON_PORTC_31,	\
			PULL_RESISTOR_ON_PORTC_31,	\
			PULLUP_OR_DOWN_ON_PORTC_31);

	#if(PORT_C_31 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTC, 	31u);
	#elif(PORT_C_31 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTC, 	31u);
	#else

	#endif


#endif


}

#endif


#if(ENABLE_PORT_D == TRUE)


inline void Port_Clear_PortD(void)
{

	PORT_PCR(PORTD, 0, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 1, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 2, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 3, 0, 0, 0, 0, 0, 0, 0);
#if(DEBUG_MODE == FALSE)
	PORT_PCR(PORTD, 4, 0, 0, 0, 0, 0, 0, 0);
#endif
	PORT_PCR(PORTD, 5, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 6, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 7, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 8, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 9, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 10, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 11, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 12, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 13, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 14, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 15, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 16, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 17, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 18, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 19, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 20, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 21, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 22, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 23, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 24, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 25, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 26, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 27, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 28, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 29, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 30, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTD, 31, 0, 0, 0, 0, 0, 0, 0);

}


inline void Port_Initialize_PortD(void)
{

	PCC-> PCCn[PCC_PORTD_INDEX] = PCC_PCCn_CGC_MASK;							/* Enable clock to PORT A*/

	Port_Clear_PortD();

	PORT_PCR(PORTD, \
			0u, \
			INTRP_TYPE_PORTD_0, \
			LOCK_REG_PORTD_0, \
			PIN_MUX_PORTD_0, \
			DRIVE_STRNTH_ON_PORTD_0, \
			PASSIVEFIL_ON_PORTD_0,	\
			PULL_RESISTOR_ON_PORTD_0,	\
			PULLUP_OR_DOWN_ON_PORTD_0);

	#if(PIN_DIR_PORTD_0 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	0u);
	#elif(PIN_DIR_PORTD_0 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	0u);
	#else

	#endif


	PORT_PCR(PORTD, \
			1u, \
			INTRP_TYPE_PORTD_1, \
			LOCK_REG_PORTD_1, \
			PIN_MUX_PORTD_1, \
			DRIVE_STRNTH_ON_PORTD_1, \
			PASSIVEFIL_ON_PORTD_1,	\
			PULL_RESISTOR_ON_PORTD_1,	\
			PULLUP_OR_DOWN_ON_PORTD_1);

	#if(PIN_DIR_PORTD_1 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	1u);
	#elif(PIN_DIR_PORTD_1 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	1u);
	#else

	#endif


	PORT_PCR(PORTD, \
	2u, \
	INTRP_TYPE_PORTD_2, \
	LOCK_REG_PORTD_2, \
	PIN_MUX_PORTD_2, \
	DRIVE_STRNTH_ON_PORTD_2, \
	PASSIVEFIL_ON_PORTD_2,	\
	PULL_RESISTOR_ON_PORTD_2,	\
	PULLUP_OR_DOWN_ON_PORTD_2);

	#if(PIN_DIR_PORTD_2 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTD, 	2u);
	#elif(PIN_DIR_PORTD_2 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTD, 	2u);
	#else

	#endif

	PORT_PCR(PORTD, \
				3u, \
				INTRP_TYPE_PORTD_3, \
				LOCK_REG_PORTD_3, \
				PIN_MUX_PORTD_3, \
				DRIVE_STRNTH_ON_PORTD_3, \
				PASSIVEFIL_ON_PORTD_3,	\
				PULL_RESISTOR_ON_PORTD_3,	\
				PULLUP_OR_DOWN_ON_PORTD_3);

	#if(PIN_DIR_PORTD_3 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTD, 	3u);
	#elif(PIN_DIR_PORTD_3 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTD, 	3u);
	#else

	#endif

	PORT_PCR(PORTD, \
				4u, \
				INTRP_TYPE_PORTD_4, \
				LOCK_REG_PORTD_4, \
				PIN_MUX_PORTD_4, \
				DRIVE_STRNTH_ON_PORTD_4, \
				PASSIVEFIL_ON_PORTD_4,	\
				PULL_RESISTOR_ON_PORTD_4,	\
				PULLUP_OR_DOWN_ON_PORTD_4);

	#if(PIN_DIR_PORTD_4 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTD, 	4u);
	#elif(PIN_DIR_PORTD_4 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTD, 	4u);
	#else

	#endif

	PORT_PCR(PORTD, \
			5u, \
			INTRP_TYPE_PORTD_5, \
			LOCK_REG_PORTD_5, \
			PIN_MUX_PORTD_5, \
			DRIVE_STRNTH_ON_PORTD_5, \
			PASSIVEFIL_ON_PORTD_5,	\
			PULL_RESISTOR_ON_PORTD_5,	\
			PULLUP_OR_DOWN_ON_PORTD_5);

	#if(PIN_DIR_PORTD_5 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	5u);
	#elif(PIN_DIR_PORTD_5 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	5u);
	#else

	#endif

	PORT_PCR(PORTD, \
			6u, \
			INTRP_TYPE_PORTD_6, \
			LOCK_REG_PORTD_6, \
			PIN_MUX_PORTD_6, \
			DRIVE_STRNTH_ON_PORTD_6, \
			PASSIVEFIL_ON_PORTD_6,	\
			PULL_RESISTOR_ON_PORTD_6,	\
			PULLUP_OR_DOWN_ON_PORTD_6);

	#if(PIN_DIR_PORTD_6 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	6u);
	#elif(PIN_DIR_PORTD_6 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	6u);
	#else

	#endif

	PORT_PCR(PORTD, \
			7u, \
			INTRP_TYPE_PORTD_7, \
			LOCK_REG_PORTD_7, \
			PIN_MUX_PORTD_7, \
			DRIVE_STRNTH_ON_PORTD_7, \
			PASSIVEFIL_ON_PORTD_7,	\
			PULL_RESISTOR_ON_PORTD_7,	\
			PULLUP_OR_DOWN_ON_PORTD_7);

	#if(PIN_DIR_PORTD_7 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	7u);
	#elif(PIN_DIR_PORTD_7 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	7u);
	#else

	#endif

	PORT_PCR(PORTD, \
			8u, \
			INTRP_TYPE_PORTD_8, \
			LOCK_REG_PORTD_8, \
			PIN_MUX_PORTD_8, \
			DRIVE_STRNTH_ON_PORTD_8, \
			PASSIVEFIL_ON_PORTD_8,	\
			PULL_RESISTOR_ON_PORTD_8,	\
			PULLUP_OR_DOWN_ON_PORTD_8);

	#if(PIN_DIR_PORTD_8 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	8u);
	#elif(PIN_DIR_PORTD_8 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	8u);
	#else

	#endif
	PORT_PCR(PORTD, \
			9u, \
			INTRP_TYPE_PORTD_9, \
			LOCK_REG_PORTD_9, \
			PIN_MUX_PORTD_9, \
			DRIVE_STRNTH_ON_PORTD_9, \
			PASSIVEFIL_ON_PORTD_9,	\
			PULL_RESISTOR_ON_PORTD_9,	\
			PULLUP_OR_DOWN_ON_PORTD_9);

	#if(PIN_DIR_PORTD_9 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	9u);
	#elif(PIN_DIR_PORTD_9 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	9u);
	#else

	#endif


	PORT_PCR(PORTD, \
			10u, \
			INTRP_TYPE_PORTD_10, \
			LOCK_REG_PORTD_10, \
			PIN_MUX_PORTD_10, \
			DRIVE_STRNTH_ON_PORTD_10, \
			PASSIVEFIL_ON_PORTD_10,	\
			PULL_RESISTOR_ON_PORTD_10,	\
			PULLUP_OR_DOWN_ON_PORTD_10);

	#if(PIN_DIR_PORTD_10 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	10u);
	#elif(PIN_DIR_PORTD_10 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	10u);
	#else

	#endif


	PORT_PCR(PORTD, \
			11u, \
			INTRP_TYPE_PORTD_11, \
			LOCK_REG_PORTD_11, \
			PIN_MUX_PORTD_11, \
			DRIVE_STRNTH_ON_PORTD_11, \
			PASSIVEFIL_ON_PORTD_11,	\
			PULL_RESISTOR_ON_PORTD_11,	\
			PULLUP_OR_DOWN_ON_PORTD_11);

	#if(PIN_DIR_PORTD_11 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	11u);
	#elif(PIN_DIR_PORTD_11 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	11u);
	#else

	#endif

	PORT_PCR(PORTD, \
			12u, \
			INTRP_TYPE_PORTD_12, \
			LOCK_REG_PORTD_12, \
			PIN_MUX_PORTD_12, \
			DRIVE_STRNTH_ON_PORTD_12, \
			PASSIVEFIL_ON_PORTD_12,	\
			PULL_RESISTOR_ON_PORTD_12,	\
			PULLUP_OR_DOWN_ON_PORTD_12);

	#if(PIN_DIR_PORTD_12 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	12u);
	#elif(PIN_DIR_PORTD_12 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	12u);
	#else

	#endif

	PORT_PCR(PORTD, \
			13u, \
			INTRP_TYPE_PORTD_13, \
			LOCK_REG_PORTD_13, \
			PIN_MUX_PORTD_13, \
			DRIVE_STRNTH_ON_PORTD_13, \
			PASSIVEFIL_ON_PORTD_13,	\
			PULL_RESISTOR_ON_PORTD_13,	\
			PULLUP_OR_DOWN_ON_PORTD_13);

	#if(PIN_DIR_PORTD_13 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	13u);
	#elif(PIN_DIR_PORTD_13 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	13u);
	#else

	#endif

	PORT_PCR(PORTD, \
			14u, \
			INTRP_TYPE_PORTD_14, \
			LOCK_REG_PORTD_14, \
			PIN_MUX_PORTD_14, \
			DRIVE_STRNTH_ON_PORTD_14, \
			PASSIVEFIL_ON_PORTD_14,	\
			PULL_RESISTOR_ON_PORTD_14,	\
			PULLUP_OR_DOWN_ON_PORTD_14);

	#if(PIN_DIR_PORTD_14 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	14u);
	#elif(PIN_DIR_PORTD_14 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	14u);
	#else

	#endif

	PORT_PCR(PORTD, \
			15u, \
			INTRP_TYPE_PORTD_15, \
			LOCK_REG_PORTD_15, \
			PIN_MUX_PORTD_15, \
			DRIVE_STRNTH_ON_PORTD_15, \
			PASSIVEFIL_ON_PORTD_15,	\
			PULL_RESISTOR_ON_PORTD_15,	\
			PULLUP_OR_DOWN_ON_PORTD_15);

	#if(PIN_DIR_PORTD_15 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	15u);
	#elif(PIN_DIR_PORTD_15 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	15u);
	#else

	#endif

	PORT_PCR(PORTD, \
			16u, \
			INTRP_TYPE_PORTD_16, \
			LOCK_REG_PORTD_16, \
			PIN_MUX_PORTD_16, \
			DRIVE_STRNTH_ON_PORTD_16, \
			PASSIVEFIL_ON_PORTD_16,	\
			PULL_RESISTOR_ON_PORTD_16,	\
			PULLUP_OR_DOWN_ON_PORTD_16);

	#if(PIN_DIR_PORTD_16 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	16u);
	#elif(PIN_DIR_PORTD_16 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	16u);
	#else

	#endif


	PORT_PCR(PORTD, \
			17u, \
			INTRP_TYPE_PORTD_17, \
			LOCK_REG_PORTD_17, \
			PIN_MUX_PORTD_17, \
			DRIVE_STRNTH_ON_PORTD_17, \
			PASSIVEFIL_ON_PORTD_17,	\
			PULL_RESISTOR_ON_PORTD_17,	\
			PULLUP_OR_DOWN_ON_PORTD_17);

	#if(PIN_DIR_PORTD_17 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	17u);
	#elif(PIN_DIR_PORTD_17 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	17u);
	#else

	#endif

#if(S32K146 | S32K148 == TRUE)

	PORT_PCR(PORTD, \
			18u, \
			INTRP_TYPE_PORTD_18, \
			LOCK_REG_PORTD_18, \
			PIN_MUX_PORTD_18, \
			DRIVE_STRNTH_ON_PORTD_18, \
			PASSIVEFIL_ON_PORTD_18,	\
			PULL_RESISTOR_ON_PORTD_18,	\
			PULLUP_OR_DOWN_ON_PORTD_18);

	#if(PIN_DIR_PORTD_18 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	18u);
	#elif(PIN_DIR_PORTD_18 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	18u);
	#else

	#endif

	PORT_PCR(PORTD, \
			19u, \
			INTRP_TYPE_PORTD_19, \
			LOCK_REG_PORTD_19, \
			PIN_MUX_PORTD_19, \
			DRIVE_STRNTH_ON_PORTD_19, \
			PASSIVEFIL_ON_PORTD_19,	\
			PULL_RESISTOR_ON_PORTD_19,	\
			PULLUP_OR_DOWN_ON_PORTD_19);

	#if(PIN_DIR_PORTD_19 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	19u);
	#elif(PIN_DIR_PORTD_19 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	19u);
	#else

	#endif

	PORT_PCR(PORTD, \
			20u, \
			INTRP_TYPE_PORTD_20, \
			LOCK_REG_PORTD_20, \
			PIN_MUX_PORTD_20, \
			DRIVE_STRNTH_ON_PORTD_20, \
			PASSIVEFIL_ON_PORTD_20,	\
			PULL_RESISTOR_ON_PORTD_20,	\
			PULLUP_OR_DOWN_ON_PORTD_20);

	#if(PIN_DIR_PORTD_20 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	20u);
	#elif(PIN_DIR_PORTD_20 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	20u);
	#else

	#endif


	PORT_PCR(PORTD, \
			21u, \
			INTRP_TYPE_PORTD_21, \
			LOCK_REG_PORTD_21, \
			PIN_MUX_PORTD_21, \
			DRIVE_STRNTH_ON_PORTD_21, \
			PASSIVEFIL_ON_PORTD_21,	\
			PULL_RESISTOR_ON_PORTD_21,	\
			PULLUP_OR_DOWN_ON_PORTD_21);

	#if(PIN_DIR_PORTD_21 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	21u);
	#elif(PIN_DIR_PORTD_21 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	21u);
	#else

	#endif

	PORT_PCR(PORTD, \
			22u, \
			INTRP_TYPE_PORTD_22, \
			LOCK_REG_PORTD_22, \
			PIN_MUX_PORTD_22, \
			DRIVE_STRNTH_ON_PORTD_22, \
			PASSIVEFIL_ON_PORTD_22,	\
			PULL_RESISTOR_ON_PORTD_22,	\
			PULLUP_OR_DOWN_ON_PORTD_22);

	#if(PIN_DIR_PORTD_22 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	22u);
	#elif(PIN_DIR_PORTD_22 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	22u);
	#else

	#endif

	PORT_PCR(PORTD, \
			23u, \
			INTRP_TYPE_PORTD_23, \
			LOCK_REG_PORTD_23, \
			PIN_MUX_PORTD_23, \
			DRIVE_STRNTH_ON_PORTD_23, \
			PASSIVEFIL_ON_PORTD_23,	\
			PULL_RESISTOR_ON_PORTD_23,	\
			PULLUP_OR_DOWN_ON_PORTD_23);

	#if(PIN_DIR_PORTD_23 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	23u);
	#elif(PIN_DIR_PORTD_23 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	23u);
	#else

	#endif

#endif

#if(S32K148 == TRUE)

	PORT_PCR(PORTD, \
			24u, \
			INTRP_TYPE_PORTD_24, \
			LOCK_REG_PORTD_24, \
			PIN_MUX_PORTD_24, \
			DRIVE_STRNTH_ON_PORTD_24, \
			PASSIVEFIL_ON_PORTD_24,	\
			PULL_RESISTOR_ON_PORTD_24,	\
			PULLUP_OR_DOWN_ON_PORTD_24);

	#if(PIN_DIR_PORTD_24 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	24u);
	#elif(PIN_DIR_PORTD_24 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	24u);
	#else

	#endif



	PORT_PCR(PORTD, \
			25u, \
			INTRP_TYPE_PORTD_25, \
			LOCK_REG_PORTD_25, \
			PIN_MUX_PORTD_25, \
			DRIVE_STRNTH_ON_PORTD_25, \
			PASSIVEFIL_ON_PORTD_25,	\
			PULL_RESISTOR_ON_PORTD_25,	\
			PULLUP_OR_DOWN_ON_PORTD_25);

	#if(PIN_DIR_PORTD_25 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	25u);
	#elif(PIN_DIR_PORTD_25 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	25u);
	#else

	#endif

	PORT_PCR(PORTD, \
			26u, \
			INTRP_TYPE_PORTD_26, \
			LOCK_REG_PORTD_26, \
			PIN_MUX_PORTD_26, \
			DRIVE_STRNTH_ON_PORTD_26, \
			PASSIVEFIL_ON_PORTD_26,	\
			PULL_RESISTOR_ON_PORTD_26,	\
			PULLUP_OR_DOWN_ON_PORTD_26);

	#if(PIN_DIR_PORTD_26 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	26u);
	#elif(PIN_DIR_PORTD_26 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	26u);
	#else

	#endif

	PORT_PCR(PORTD, \
			27u, \
			INTRP_TYPE_PORTD_27, \
			LOCK_REG_PORTD_27, \
			PIN_MUX_PORTD_27, \
			DRIVE_STRNTH_ON_PORTD_27, \
			PASSIVEFIL_ON_PORTD_27,	\
			PULL_RESISTOR_ON_PORTD_27,	\
			PULLUP_OR_DOWN_ON_PORTD_27);

	#if(PIN_DIR_PORTD_27 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	27u);
	#elif(PIN_DIR_PORTD_27 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	27u);
	#else

	#endif

	PORT_PCR(PORTD, \
			28u, \
			INTRP_TYPE_PORTD_28, \
			LOCK_REG_PORTD_28, \
			PIN_MUX_PORTD_28, \
			DRIVE_STRNTH_ON_PORTD_28, \
			PASSIVEFIL_ON_PORTD_28,	\
			PULL_RESISTOR_ON_PORTD_28,	\
			PULLUP_OR_DOWN_ON_PORTD_28);

	#if(PIN_DIR_PORTD_28 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	28u);
	#elif(PIN_DIR_PORTD_28 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	28u);
	#else

	#endif

	PORT_PCR(PORTD, \
			29u, \
			INTRP_TYPE_PORTD_29, \
			LOCK_REG_PORTD_29, \
			PIN_MUX_PORTD_29, \
			DRIVE_STRNTH_ON_PORTD_29, \
			PASSIVEFIL_ON_PORTD_29,	\
			PULL_RESISTOR_ON_PORTD_29,	\
			PULLUP_OR_DOWN_ON_PORTD_29);

	#if(PIN_DIR_PORTD_29 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	29u);
	#elif(PIN_DIR_PORTD_29 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	29u);
	#else

	#endif

	PORT_PCR(PORTD, \
			30u, \
			INTRP_TYPE_PORTD_30, \
			LOCK_REG_PORTD_30, \
			PIN_MUX_PORTD_30, \
			DRIVE_STRNTH_ON_PORTD_30, \
			PASSIVEFIL_ON_PORTD_30,	\
			PULL_RESISTOR_ON_PORTD_30,	\
			PULLUP_OR_DOWN_ON_PORTD_30);

	#if(PIN_DIR_PORTD_30 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	30u);
	#elif(PIN_DIR_PORTD_30 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	30u);
	#else

	#endif


	PORT_PCR(PORTD, \
			31u, \
			INTRP_TYPE_PORTD_31, \
			LOCK_REG_PORTD_31, \
			PIN_MUX_PORTD_31, \
			DRIVE_STRNTH_ON_PORTD_31, \
			PASSIVEFIL_ON_PORTD_31,	\
			PULL_RESISTOR_ON_PORTD_31,	\
			PULLUP_OR_DOWN_ON_PORTD_31);

	#if(PIN_DIR_PORTD_31 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTD, 	31u);
	#elif(PIN_DIR_PORTD_31 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTD, 	31u);
	#else

	#endif

#endif

}


#endif

#if(ENABLE_PORT_E == TRUE)

inline void Port_Clear_PortE(void)
{

	PORT_PCR(PORTE, 0, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 1, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 2, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 3, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 4, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 5, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 6, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 7, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 8, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 9, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 10, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 11, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 12, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 13, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 14, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 15, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 16, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 17, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 18, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 19, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 20, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 21, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 22, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 23, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 24, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 25, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 26, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 27, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 28, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 29, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 30, 0, 0, 0, 0, 0, 0, 0);
	PORT_PCR(PORTE, 31, 0, 0, 0, 0, 0, 0, 0);

}



inline void Port_Initialize_PortE(void)
{

	PCC-> PCCn[PCC_PORTE_INDEX] = PCC_PCCn_CGC_MASK;							/* Enable clock to PORT A*/

	Port_Clear_PortE();

	PORT_PCR(PORTE, \
			0u, \
			INTRP_TYPE_PORTE_0, \
			LOCK_REG_PORTE_0, \
			PIN_MUX_PORTE_0, \
			DRIVE_STRNTH_ON_PORTE_0, \
			PASSIVEFIL_ON_PORTE_0,	\
			PULL_RESISTOR_ON_PORTE_0,	\
			PULLUP_OR_DOWN_ON_PORTE_0);

	#if(PORT_E_0 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	0u);
	#elif(PORT_E_0 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	0u);
	#else

	#endif


	PORT_PCR(PORTE, \
			1u, \
			INTRP_TYPE_PORTE_1, \
			LOCK_REG_PORTE_1, \
			PIN_MUX_PORTE_1, \
			DRIVE_STRNTH_ON_PORTE_1, \
			PASSIVEFIL_ON_PORTE_1,	\
			PULL_RESISTOR_ON_PORTE_1,	\
			PULLUP_OR_DOWN_ON_PORTE_1);

	#if(PORT_E_1 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	1u);
	#elif(PORT_E_1 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	1u);
	#else

	#endif


	PORT_PCR(PORTE, \
	1u, \
	INTRP_TYPE_PORTE_2, \
	LOCK_REG_PORTE_2, \
	PIN_MUX_PORTE_2, \
	DRIVE_STRNTH_ON_PORTE_2, \
	PASSIVEFIL_ON_PORTE_2,	\
	PULL_RESISTOR_ON_PORTE_2,	\
	PULLUP_OR_DOWN_ON_PORTE_2);

	#if(PORT_E_2 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTE, 	2u);
	#elif(PORT_E_2 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTE, 	2u);
	#else

	#endif

	PORT_PCR(PORTE, \
				1u, \
				INTRP_TYPE_PORTE_3, \
				LOCK_REG_PORTE_3, \
				PIN_MUX_PORTE_3, \
				DRIVE_STRNTH_ON_PORTE_3, \
				PASSIVEFIL_ON_PORTE_3,	\
				PULL_RESISTOR_ON_PORTE_3,	\
				PULLUP_OR_DOWN_ON_PORTE_3);

	#if(PORT_E_3 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTE, 	3u);
	#elif(PORT_E_3 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTE, 	3u);
	#else

	#endif

	PORT_PCR(PORTE, \
				1u, \
				INTRP_TYPE_PORTE_4, \
				LOCK_REG_PORTE_4, \
				PIN_MUX_PORTE_4, \
				DRIVE_STRNTH_ON_PORTE_4, \
				PASSIVEFIL_ON_PORTE_4,	\
				PULL_RESISTOR_ON_PORTE_4,	\
				PULLUP_OR_DOWN_ON_PORTE_4);

	#if(PORT_E_4 == INPUT)
	SET_PIN_DIRECTION_INPUT(PTE, 	4u);
	#elif(PORT_E_4 == OUTPUT)
	SET_PIN_DIRECTION_OUTPUT(PTE, 	4u);
	#else

	#endif

	PORT_PCR(PORTE, \
			5u, \
			INTRP_TYPE_PORTE_5, \
			LOCK_REG_PORTE_5, \
			PIN_MUX_PORTE_5, \
			DRIVE_STRNTH_ON_PORTE_5, \
			PASSIVEFIL_ON_PORTE_5,	\
			PULL_RESISTOR_ON_PORTE_5,	\
			PULLUP_OR_DOWN_ON_PORTE_5);

	#if(PORT_E_5 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	5u);
	#elif(PORT_E_5 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	5u);
	#else

	#endif

	PORT_PCR(PORTE, \
			8u, \
			INTRP_TYPE_PORTE_6, \
			LOCK_REG_PORTE_6, \
			PIN_MUX_PORTE_6, \
			DRIVE_STRNTH_ON_PORTE_6, \
			PASSIVEFIL_ON_PORTE_6,	\
			PULL_RESISTOR_ON_PORTE_6,	\
			PULLUP_OR_DOWN_ON_PORTE_6);

	#if(PORT_E_6 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	6u);
	#elif(PORT_E_6 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	6u);
	#else

	#endif

	PORT_PCR(PORTE, \
			8u, \
			INTRP_TYPE_PORTE_7, \
			LOCK_REG_PORTE_7, \
			PIN_MUX_PORTE_7, \
			DRIVE_STRNTH_ON_PORTE_7, \
			PASSIVEFIL_ON_PORTE_7,	\
			PULL_RESISTOR_ON_PORTE_7,	\
			PULLUP_OR_DOWN_ON_PORTE_7);

	#if(PORT_E_7 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	7u);
	#elif(PORT_E_7 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	7u);
	#else

	#endif

	PORT_PCR(PORTE, \
			8u, \
			INTRP_TYPE_PORTE_8, \
			LOCK_REG_PORTE_8, \
			PIN_MUX_PORTE_8, \
			DRIVE_STRNTH_ON_PORTE_8, \
			PASSIVEFIL_ON_PORTE_8,	\
			PULL_RESISTOR_ON_PORTE_8,	\
			PULLUP_OR_DOWN_ON_PORTE_8);

	#if(PORT_E_8 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	8u);
	#elif(PORT_E_8 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	8u);
	#else

	#endif
	PORT_PCR(PORTE, \
			9u, \
			INTRP_TYPE_PORTE_9, \
			LOCK_REG_PORTE_9, \
			PIN_MUX_PORTE_9, \
			DRIVE_STRNTH_ON_PORTE_9, \
			PASSIVEFIL_ON_PORTE_9,	\
			PULL_RESISTOR_ON_PORTE_9,	\
			PULLUP_OR_DOWN_ON_PORTE_9);

	#if(PORT_E_9 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	9u);
	#elif(PORT_E_9 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	9u);
	#else

	#endif


	PORT_PCR(PORTE, \
			10u, \
			INTRP_TYPE_PORTE_10, \
			LOCK_REG_PORTE_10, \
			PIN_MUX_PORTE_10, \
			DRIVE_STRNTH_ON_PORTE_10, \
			PASSIVEFIL_ON_PORTE_10,	\
			PULL_RESISTOR_ON_PORTE_10,	\
			PULLUP_OR_DOWN_ON_PORTE_10);

	#if(PORT_E_10 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	10u);
	#elif(PORT_E_10 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	10u);
	#else

	#endif


	PORT_PCR(PORTE, \
			11u, \
			INTRP_TYPE_PORTE_11, \
			LOCK_REG_PORTE_11, \
			PIN_MUX_PORTE_11, \
			DRIVE_STRNTH_ON_PORTE_11, \
			PASSIVEFIL_ON_PORTE_11,	\
			PULL_RESISTOR_ON_PORTE_11,	\
			PULLUP_OR_DOWN_ON_PORTE_11);

	#if(PORT_E_11 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	11u);
	#elif(PORT_E_11 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	11u);
	#else

	#endif

	PORT_PCR(PORTE, \
			12u, \
			INTRP_TYPE_PORTE_12, \
			LOCK_REG_PORTE_12, \
			PIN_MUX_PORTE_12, \
			DRIVE_STRNTH_ON_PORTE_12, \
			PASSIVEFIL_ON_PORTE_12,	\
			PULL_RESISTOR_ON_PORTE_12,	\
			PULLUP_OR_DOWN_ON_PORTE_12);

	#if(PORT_E_12 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	12u);
	#elif(PORT_E_12 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	12u);
	#else

	#endif

	PORT_PCR(PORTE, \
			13u, \
			INTRP_TYPE_PORTE_13, \
			LOCK_REG_PORTE_13, \
			PIN_MUX_PORTE_13, \
			DRIVE_STRNTH_ON_PORTE_13, \
			PASSIVEFIL_ON_PORTE_13,	\
			PULL_RESISTOR_ON_PORTE_13,	\
			PULLUP_OR_DOWN_ON_PORTE_13);

	#if(PORT_E_13 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	13u);
	#elif(PORT_E_13 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	13u);
	#else

	#endif

	PORT_PCR(PORTE, \
			14u, \
			INTRP_TYPE_PORTE_14, \
			LOCK_REG_PORTE_14, \
			PIN_MUX_PORTE_14, \
			DRIVE_STRNTH_ON_PORTE_14, \
			PASSIVEFIL_ON_PORTE_14,	\
			PULL_RESISTOR_ON_PORTE_14,	\
			PULLUP_OR_DOWN_ON_PORTE_14);

	#if(PORT_E_14 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	14u);
	#elif(PORT_E_14 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	14u);
	#else

	#endif

	PORT_PCR(PORTE, \
			15u, \
			INTRP_TYPE_PORTE_15, \
			LOCK_REG_PORTE_15, \
			PIN_MUX_PORTE_15, \
			DRIVE_STRNTH_ON_PORTE_15, \
			PASSIVEFIL_ON_PORTE_15,	\
			PULL_RESISTOR_ON_PORTE_15,	\
			PULLUP_OR_DOWN_ON_PORTE_15);

	#if(PORT_E_15 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	15u);
	#elif(PORT_E_15 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	15u);
	#else

	#endif

	PORT_PCR(PORTE, \
			16u, \
			INTRP_TYPE_PORTE_16, \
			LOCK_REG_PORTE_16, \
			PIN_MUX_PORTE_16, \
			DRIVE_STRNTH_ON_PORTE_16, \
			PASSIVEFIL_ON_PORTE_16,	\
			PULL_RESISTOR_ON_PORTE_16,	\
			PULLUP_OR_DOWN_ON_PORTE_16);

	#if(PORT_E_16 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	16u);
	#elif(PORT_E_16 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	16u);
	#else

	#endif


	PORT_PCR(PORTE, \
			17u, \
			INTRP_TYPE_PORTE_17, \
			LOCK_REG_PORTE_17, \
			PIN_MUX_PORTE_17, \
			DRIVE_STRNTH_ON_PORTE_17, \
			PASSIVEFIL_ON_PORTE_17,	\
			PULL_RESISTOR_ON_PORTE_17,	\
			PULLUP_OR_DOWN_ON_PORTE_17);

	#if(PORT_E_17 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	17u);
	#elif(PORT_E_17 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	17u);
	#else

	#endif

	PORT_PCR(PORTE, \
			18u, \
			INTRP_TYPE_PORTE_18, \
			LOCK_REG_PORTE_18, \
			PIN_MUX_PORTE_18, \
			DRIVE_STRNTH_ON_PORTE_18, \
			PASSIVEFIL_ON_PORTE_18,	\
			PULL_RESISTOR_ON_PORTE_18,	\
			PULLUP_OR_DOWN_ON_PORTE_18);

	#if(PORT_E_18 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	18u);
	#elif(PORT_E_18 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	18u);
	#else

	#endif

	PORT_PCR(PORTE, \
			19u, \
			INTRP_TYPE_PORTE_19, \
			LOCK_REG_PORTE_19, \
			PIN_MUX_PORTE_19, \
			DRIVE_STRNTH_ON_PORTE_19, \
			PASSIVEFIL_ON_PORTE_19,	\
			PULL_RESISTOR_ON_PORTE_19,	\
			PULLUP_OR_DOWN_ON_PORTE_19);

	#if(PORT_E_19 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	19u);
	#elif(PORT_E_19 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	19u);
	#else

	#endif

	PORT_PCR(PORTE, \
			20u, \
			INTRP_TYPE_PORTE_20, \
			LOCK_REG_PORTE_20, \
			PIN_MUX_PORTE_20, \
			DRIVE_STRNTH_ON_PORTE_20, \
			PASSIVEFIL_ON_PORTE_20,	\
			PULL_RESISTOR_ON_PORTE_20,	\
			PULLUP_OR_DOWN_ON_PORTE_20);

	#if(PORT_E_20 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	20u);
	#elif(PORT_E_20 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	20u);
	#else

	#endif


	PORT_PCR(PORTE, \
			21u, \
			INTRP_TYPE_PORTE_21, \
			LOCK_REG_PORTE_21, \
			PIN_MUX_PORTE_21, \
			DRIVE_STRNTH_ON_PORTE_21, \
			PASSIVEFIL_ON_PORTE_21,	\
			PULL_RESISTOR_ON_PORTE_21,	\
			PULLUP_OR_DOWN_ON_PORTE_21);

	#if(PORT_E_21 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	21u);
	#elif(PORT_E_21 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	21u);
	#else

	#endif

	PORT_PCR(PORTE, \
			22u, \
			INTRP_TYPE_PORTE_22, \
			LOCK_REG_PORTE_22, \
			PIN_MUX_PORTE_22, \
			DRIVE_STRNTH_ON_PORTE_22, \
			PASSIVEFIL_ON_PORTE_22,	\
			PULL_RESISTOR_ON_PORTE_22,	\
			PULLUP_OR_DOWN_ON_PORTE_22);

	#if(PORT_E_22 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	22u);
	#elif(PORT_E_22 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	22u);
	#else

	#endif

	PORT_PCR(PORTE, \
			23u, \
			INTRP_TYPE_PORTE_23, \
			LOCK_REG_PORTE_23, \
			PIN_MUX_PORTE_23, \
			DRIVE_STRNTH_ON_PORTE_23, \
			PASSIVEFIL_ON_PORTE_23,	\
			PULL_RESISTOR_ON_PORTE_23,	\
			PULLUP_OR_DOWN_ON_PORTE_23);

	#if(PORT_E_23 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	23u);
	#elif(PORT_E_23 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	23u);
	#else

	#endif


	PORT_PCR(PORTE, \
			24u, \
			INTRP_TYPE_PORTE_24, \
			LOCK_REG_PORTE_24, \
			PIN_MUX_PORTE_24, \
			DRIVE_STRNTH_ON_PORTE_24, \
			PASSIVEFIL_ON_PORTE_24,	\
			PULL_RESISTOR_ON_PORTE_24,	\
			PULLUP_OR_DOWN_ON_PORTE_24);

	#if(PORT_E_24 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	24u);
	#elif(PORT_E_24 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	24u);
	#else

	#endif



	PORT_PCR(PORTE, \
			25u, \
			INTRP_TYPE_PORTE_25, \
			LOCK_REG_PORTE_25, \
			PIN_MUX_PORTE_25, \
			DRIVE_STRNTH_ON_PORTE_25, \
			PASSIVEFIL_ON_PORTE_25,	\
			PULL_RESISTOR_ON_PORTE_25,	\
			PULLUP_OR_DOWN_ON_PORTE_25);

	#if(PORT_E_25 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	25u);
	#elif(PORT_E_25 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	25u);
	#else

	#endif

	PORT_PCR(PORTE, \
			26u, \
			INTRP_TYPE_PORTE_26, \
			LOCK_REG_PORTE_26, \
			PIN_MUX_PORTE_26, \
			DRIVE_STRNTH_ON_PORTE_26, \
			PASSIVEFIL_ON_PORTE_26,	\
			PULL_RESISTOR_ON_PORTE_26,	\
			PULLUP_OR_DOWN_ON_PORTE_26);

	#if(PORT_E_26 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	26u);
	#elif(PORT_E_26 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	26u);
	#else

	#endif

	PORT_PCR(PORTE, \
			27u, \
			INTRP_TYPE_PORTE_27, \
			LOCK_REG_PORTE_27, \
			PIN_MUX_PORTE_27, \
			DRIVE_STRNTH_ON_PORTE_27, \
			PASSIVEFIL_ON_PORTE_27,	\
			PULL_RESISTOR_ON_PORTE_27,	\
			PULLUP_OR_DOWN_ON_PORTE_27);

	#if(PORT_E_27 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	27u);
	#elif(PORT_E_27 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	27u);
	#else

	#endif

	PORT_PCR(PORTE, \
			28u, \
			INTRP_TYPE_PORTE_28, \
			LOCK_REG_PORTE_28, \
			PIN_MUX_PORTE_28, \
			DRIVE_STRNTH_ON_PORTE_28, \
			PASSIVEFIL_ON_PORTE_28,	\
			PULL_RESISTOR_ON_PORTE_28,	\
			PULLUP_OR_DOWN_ON_PORTE_28);

	#if(PORT_E_28 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	28u);
	#elif(PORT_E_28 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	28u);
	#else

	#endif

	PORT_PCR(PORTE, \
			29u, \
			INTRP_TYPE_PORTE_29, \
			LOCK_REG_PORTE_29, \
			PIN_MUX_PORTE_29, \
			DRIVE_STRNTH_ON_PORTE_29, \
			PASSIVEFIL_ON_PORTE_29,	\
			PULL_RESISTOR_ON_PORTE_29,	\
			PULLUP_OR_DOWN_ON_PORTE_29);

	#if(PORT_E_29 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	29u);
	#elif(PORT_E_29 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	29u);
	#else

	#endif

	PORT_PCR(PORTE, \
			30u, \
			INTRP_TYPE_PORTE_30, \
			LOCK_REG_PORTE_30, \
			PIN_MUX_PORTE_30, \
			DRIVE_STRNTH_ON_PORTE_30, \
			PASSIVEFIL_ON_PORTE_30,	\
			PULL_RESISTOR_ON_PORTE_30,	\
			PULLUP_OR_DOWN_ON_PORTE_30);

	#if(PORT_E_30 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	30u);
	#elif(PORT_E_30 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	30u);
	#else

	#endif


	PORT_PCR(PORTE, \
			31u, \
			INTRP_TYPE_PORTE_31, \
			LOCK_REG_PORTE_31, \
			PIN_MUX_PORTE_31, \
			DRIVE_STRNTH_ON_PORTE_31, \
			PASSIVEFIL_ON_PORTE_31,	\
			PULL_RESISTOR_ON_PORTE_31,	\
			PULLUP_OR_DOWN_ON_PORTE_31);

	#if(PORT_E_31 == INPUT)
			SET_PIN_DIRECTION_INPUT(PTE, 	31u);
	#elif(PORT_E_31 == OUTPUT)
			SET_PIN_DIRECTION_OUTPUT(PTE, 	31u);
	#else

	#endif


}

#endif


/* Interrupt handlers */


void INTERRUPT_	PORTC_IRQHandler(void)// Function pointer from IV-Table Library -> Startup_S32K144.S
{

	if(ENABLE == PORT_PCR_READ_INTRPT(PORTC, 12u))
	{
		PORT_PCR_CLR_INTRPT(PORTC, 12u);// SW 2 -> S32k144 Evaluation kit
	}
	else
	{

	}

	if(ENABLE == PORT_PCR_READ_INTRPT(PORTC, 13u))
	{
		PORT_PCR_CLR_INTRPT(PORTC, 13u);// SW 3 -> S32k144 Evaluation kit
	}
	else
	{

	}

}

