/*
 * ADC_Cfg.h
 *
 *  Created on: 07-Dec-2020
 *      Author: HP
 */

#ifndef MCAL_ADC_CFG_H_
#define MCAL_ADC_CFG_H_


//ADC_Cfg.h


#define	ADC0_MODULE											ENABLE
#define	ADC1_MODULE											ENABLE


/**********************************ADC0_MODULE**************************************************/

#if(ENABLE	==	ADC0_MODULE)

	#define 	ADC0_CHANNEL_0									ENABLE
	#define 	ADC0_CHANNEL_1									DISABLE
	#define 	ADC0_CHANNEL_2									DISABLE
	#define 	ADC0_CHANNEL_3									DISABLE
	#define 	ADC0_CHANNEL_4									DISABLE
	#define 	ADC0_CHANNEL_5									DISABLE
	#define		ADC0_CHANNEL_6									DISABLE
	#define 	ADC0_CHANNEL_7									DISABLE
	#define 	ADC0_CHANNEL_8									DISABLE
	#define 	ADC0_CHANNEL_9									DISABLE
	#define		ADC0_CHANNEL_10									DISABLE
	#define 	ADC0_CHANNEL_11									DISABLE
	#define 	ADC0_CHANNEL_12									DISABLE
	#define 	ADC0_CHANNEL_13									DISABLE
	#define 	ADC0_CHANNEL_14									DISABLE
	#define 	ADC0_CHANNEL_15									DISABLE

	#define		ADC0_CFG2_SAMPLERATE							12u	/*Allowed range 2-256 TBD, refer manual 1228*/

	#define		ADC0_CFG1_MODE_DIV								ADCn_CFG1_MODE_8BIT
	#define		ADC0_CFG1_ADIV_DIV								ADCn_CFG1_ADIV_DIV8
	#define		ADC0_CFG1_ADICLK								ADCn_CFG1_ADICLK_1

	#define		ADC0_CHANNEL_0_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_1_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_2_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_3_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_4_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_5_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_6_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_7_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_8_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_9_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_10_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_11_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_12_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_13_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_14_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC0_CHANNEL_15_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT

	#define 	ADC0_CHANNEL_0_INTRPT							ENABLE
	#define 	ADC0_CHANNEL_1_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_2_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_3_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_4_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_5_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_6_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_7_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_8_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_9_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_10_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_11_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_12_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_13_INTRPT							DISABLE
	#define		ADC0_CHANNEL_14_INTRPT							DISABLE
	#define 	ADC0_CHANNEL_15_INTRPT							DISABLE

	#define		ADC0_CONV_TRIGSEL								ADCn_SC2_CONVTRIGSW
	#define		ADC0_REFVTGSELECT_CFG							ADCn_SC2_REF_SELDEFAULT
	#define		ADC0_COMP_GREATER								DISABLE
	#define		ADC0_COMP_RANGE									DISABLE
	#define		ADC0_DMA_ACCESS									DISABLE
	#define		ADC0_COMPFUNCTION								DISABLE

	#define		ADC0_CONTI_CONV									ENABLE
	#define		ADC0_HW_AVG_CFG									DISABLE
	#define		ADC0_HW_AVG_SEL									ADCn_SC3_HWAVGBY4SAMPLES

#endif

/**********************************ADC1_MODULE**************************************************/

#if(ENABLE	==	ADC1_MODULE)


	#define 	ADC1_CHANNEL_0									ENABLE
	#define 	ADC1_CHANNEL_1									DISABLE
	#define 	ADC1_CHANNEL_2									DISABLE
	#define 	ADC1_CHANNEL_3									DISABLE
	#define 	ADC1_CHANNEL_4									DISABLE
	#define 	ADC1_CHANNEL_5									DISABLE
	#define		ADC1_CHANNEL_6									DISABLE
	#define 	ADC1_CHANNEL_7									DISABLE
	#define 	ADC1_CHANNEL_8									DISABLE
	#define 	ADC1_CHANNEL_9									DISABLE
	#define		ADC1_CHANNEL_10									DISABLE
	#define 	ADC1_CHANNEL_11									DISABLE
	#define 	ADC1_CHANNEL_12									DISABLE
	#define 	ADC0_CHANNEL_13									DISABLE
	#define 	ADC0_CHANNEL_14									DISABLE
	#define 	ADC0_CHANNEL_15									DISABLE

	#define		ADC1_CFG2_SAMPLERATE							12u	/*Allowed range 2-256 TBD, refer manual 1228*/

	#define		ADC1_CFG1_MODE_DIV								ADCn_CFG1_MODE_8BIT
	#define		ADC1_CFG1_ADIV_DIV								ADCn_CFG1_ADIV_DIV8
	#define		ADC1_CFG1_ADICLK								ADCn_CFG1_ADICLK_1

	#define		ADC1_CHANNEL_0_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_1_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_2_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_3_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_4_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_5_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_6_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_7_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_8_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_9_ADCH								ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_10_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_11_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_12_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_13_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_14_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT
	#define		ADC1_CHANNEL_15_ADCH							ADCn_SC1_ADCH_EXTCH0ASINPUT

	#define 	ADC1_CHANNEL_0_INTRPT							ENABLE
	#define 	ADC1_CHANNEL_1_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_2_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_3_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_4_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_5_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_6_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_7_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_8_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_9_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_10_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_11_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_12_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_13_INTRPT							DISABLE
	#define		ADC1_CHANNEL_14_INTRPT							DISABLE
	#define 	ADC1_CHANNEL_15_INTRPT							DISABLE

	#define		ADC1_CONV_TRIGSEL								ADCn_SC2_CONVTRIGSW
	#define		ADC1_REFVTGSELECT_CFG							ADCn_SC2_REF_SELDEFAULT
	#define		ADC1_COMP_GREATER								DISABLE
	#define		ADC1_COMP_RANGE									DISABLE
	#define		ADC1_DMA_ACCESS									DISABLE
	#define		ADC1_COMPFUNCTION								DISABLE

	#define		ADC1_CONTI_CONV									ENABLE
	#define		ADC1_HW_AVG_CFG									DISABLE
	#define		ADC1_HW_AVG_SEL									ADCn_SC3_HWAVGBY4SAMPLES

#endif


#endif /* MCAL_ADC_CFG_H_ */
